### PR TITLE
Multiple discord channels

### PR DESCRIPTION
**Pull request by Ionys320**
Add the possibilities to have multiple discord channels and not only one.

### CODE REVIEW

**Comment by Ionys320** [comment]
Maybe it's not fully okay, but I cant test because I dont have a 3D printer.

**Comment by bchanudet** [comment]
Hello,

Thanks for the PR, however, that's an awful lot of commits to review, and seeing that @cameroncros is mentioned in the commit list, I have the impression this Pull Request was more destined to be sent to cameroncros/OctoPrint-DiscordRemote ?

Also, even without a 3D Printer, Octoprint and the plugin can be tested by using the Virtual Printer : https://docs.octoprint.org/en/master/development/virtual_printer.html

**Comment by cameroncros** [comment]
This was definitely for me I think.

**Comment by bchanudet** [comment]
Thanks for your feedback :)

I've seen you re-created the PR in DiscordRemote, so I'll close this one.

**Pull request closed without merging**
